### ISSUE TITLE
Some artifacts missing for a more complex app

### ISSUE THREAD

**Issue by ludoch** [sdeleuze/spring-boot-crac-demo#1]
Thanks for the sample, its working for me...
I tried to apply it to a more complex Springboot app. and I get build error:
```
The POM for org.springframework:spring-oxm:jar:6.1.0-SNAPSHOT is missing, no dependency information available
The POM for org.springframework:spring-jdbc:jar:6.1.0-SNAPSHOT is missing, no dependency information available
The POM for org.springframework:spring-messaging:jar:6.1.0-SNAPSHOT is missing, no dependency information available
The POM for org.springframework:spring-tx:jar:6.1.0-SNAPSHOT is missing, no dependency information available
```

When I remove  
       ` <spring-framework.version>6.1.0-SNAPSHOT</spring-framework.version>`
from my pom.xml, the app compiles, but when I run the container, I now have a crac error:

 ```
2023-05-19T15:29:35.160Z  INFO [,,] 129 --- [Attach Listener] jdk.crac                                 : /opt/app/fordtestappfromludoandford-1.0-SNAPSHOT.jar is recorded as always available on restore
An exception during a checkpoint operation:
jdk.internal.crac.CheckpointException
	at java.base/jdk.internal.crac.Core.checkpointRestore1(Core.java:141)
	at java.base/jdk.internal.crac.Core.checkpointRestore(Core.java:246)
	at java.base/jdk.internal.crac.Core.checkpointRestoreInternal(Core.java:262)
	Suppressed: jdk.internal.crac.impl.CheckpointOpenSocketException: tcp localAddr 0.0.0.0 localPort 8080 remoteAddr 0.0.0.0 remotePort 0
		at java.base/jdk.internal.crac.Core.translateJVMExceptions(Core.java:91)
		at java.base/jdk.internal.crac.Core.checkpointRestore1(Core.java:145)
		... 2 more

```

Any hints to make progress? Thanks!

**Comment by ludoch** [comment]
Made progress with overwrite these entries in my pom.xml

 ```
  <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>6.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>6.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>6.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>6.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-expression</artifactId>
            <version>6.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jcl</artifactId>
            <version>6.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>6.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>6.1.0-SNAPSHOT</version>
        </dependency>
```

Now the scripts do not work automatically for me, but I could start the container with first sh to it and run the entrypoint then from another terminal, capture the new image.
Will try in 'prod' soon.

**Comment by sdeleuze** [comment]
`<spring-framework.version>6.1.0-SNAPSHOT</spring-framework.version>` is required to get checkpoint/restore support, and should be equivalent to providing versions for each dependencies if:
 - You are using [Spring Boot parent POM](https://github.com/sdeleuze/spring-boot-crac-demo/blob/main/pom.xml#L5-L11).
 - You declare [the Snapshot repository](https://github.com/sdeleuze/spring-boot-crac-demo/blob/main/pom.xml#L96-L105).
